### ISSUE TITLE
Bookmarks configuration does not work anymore after YCast 1.1.5 update

### ISSUE THREAD

**Issue by mvdwetering** [casperklein/homeassistant-addons#22]
**Add-on name**
YCast 1.1.5

**Describe the bug**

The bookmarks I had in my configuration are not working anymore. Home Assistant seems to indicate the format is invalid.
Also copy-pasting the example from the README.md does not work and gives the same error.

**To Reproduce**

1. I think it was something like this
2. Make a bookmarks configuration in previous version
3. Upgrade to 1.1.5
4. Bookrmarks not working

I did notice some kind of error when updating, but then I tried to fix the configuration by resetting the configuration to defaults and now I can't get the bookmarks back in.

**Expected behavior**

Bookmarks configuration keeps working after update or instructions on how to migrate to a new format.

**Screenshots**

![image](https://github.com/user-attachments/assets/e3527f68-debc-441f-a13b-9c7e96f64ebc)

This is the error I see when trying to save the configuration. It translates to "Failed to save addon configuration: not a valid value. Got { 'bookmarkd': etc..."

**Additional context**

My configuration that worked before:

```yaml
bookmarks:
  - "Rock Antenne: http://mp3channels.webradio.rockantenne.de/rockantenne"
  - "NPO Radio 1: https://icecast.omroep.nl/radio1-bb-mp3"
  - "NPO Radio 2: https://icecast.omroep.nl/radio2-bb-mp3"
  - "3FM: http://icecast.omroep.nl/3fm-bb-mp3"
  - "NPO Radio 4: https://icecast.omroep.nl/radio4-bb-mp3"
  - "NPO Radio 5: https://icecast.omroep.nl/radio5-bb-mp3"
  - "Radio 538: https://25283.live.streamtheworld.com/RADIO538.mp3"
  - >-
    Radio 10:  
    http://playerservices.streamtheworld.com/api/livestream-redirect/RADIO10.mp3
  - "Qmusic: https://icecast-qmusicnl-cdp.triple-it.nl/Qmusic_nl_live_96.mp3"
  - "SLAM!: http://stream.slam.nl/slam"
  - "100% NL: http://stream.100p.nl/100pctnl.mp3"
  - >-
    KINK:
    https://playerservices.streamtheworld.com/api/livestream-redirect/KINK.mp3
  - "Arrow Classic Rock: http://stream.gal.io/arrow"
  - "BNR Nieuwsradio: https://stream.bnr.nl/bnr_mp3_128_20"
  - "Sky Radio: https://22663.live.streamtheworld.com/SKYRADIO.mp3"
  - >-
    Radio Veronica:
    https://playerservices.streamtheworld.com/api/livestream-redirect/VERONICA.mp3
```
